name: Tests

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - name: LFS install
      shell: bash
      run: git lfs install --skip-smudge
    - uses: actions/checkout@v2
      with:
        lfs: false
    - name: LFS pull
      shell: bash
      run: |
        git lfs pull
        git lfs install --force
    - name: Install pods
      shell: bash
      run: pod install
    - name: Build for testing
      run: xcodebuild build-for-testing -workspace "ID Capture.xcworkspace" -scheme "ID Capture" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty
    - name: Run tests
      run: xcodebuild test -workspace "ID Capture.xcworkspace" -scheme "ID Capture" -sdk iphonesimulator -configuration Debug -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty
